### ISSUE TITLE
Cannot install on 2.2.6

### ISSUE THREAD

**Issue by henk-hypershop** [yireo/Yireo_LinkPreload#14]
Hi,

I tried to install this composer package on 2.2.6, but cannot continue:

 [InvalidArgumentException]                                                                                                                                                              
  Could not find a version of package yireo/magento2-serverpush matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by jissereitsma** [comment]
This could be due to the fact how semantic versioning works. A stable version starts from `1.x`. This extension uses `0.x` because the Server Push feature is experimental in most (if not all) webservers. Therefore, you will need to make sure that your composer file supports other versions than just stable versions.

**Comment by jissereitsma** [comment]
https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by henk-hypershop** [comment]
Yes, i have figured that out. Since this is experimental, i will let this one pass. Thanks for your reply!
