### ISSUE TITLE
Cookie to avoid ServerPush on second request

### ISSUE THREAD

**Issue by onlinebizsoft** [yireo/Yireo_LinkPreload#19]
Technically I don't think this work? Because Magento has varnish in front so after first request served by Magento, I believe Varnish will respond with same header for second request?

If Varnish configured to exclude this header part then this cookie feature is not needed then.

**Comment by jissereitsma** [comment]
Good point. So, technical this works. The question would be if this works with Varnish as well. Please note that the majority of M2 shops (in my personal experience) are running without Varnish, so for those shops, there is nothing needed.

As for Varnish specifically, this solution makes less sense in the case of an FPC-compatible page. However, by default, FPC is disabled for many other pages (customer, cart, checkout, etc) where this extension still becomes handy. In short, the cookie feature is needed in all of those cases where Varnish is not used, plus all of those cases where Varnish is used but a page is not in the FPC.

Another question is whether Varnish supports ServerPush. It does not: ServerPush is an HTTP/2 feature which requires SSL and Varnish does not support SSL. An SSL terminator like HAProxy, Hitch or even Nginx would be needed for SSL, and for sure HAProxy and Nginx support ServerPush. The question is too complex to ask here and actually relates little to this extension itself.

I'll close this issue now because no problem was raised. It was just a question on whether this Magento 2 extension is useful in those edge-cases where Varnish supports FPC and indeed it does not. But that's unrelated to the Magento 2 extension which works and adds benefit to a lot of other situations.

**Comment by onlinebizsoft** [comment]
@jissereitsma I agree that this feature can be still helpful in some cases where Varnish is not used. But do we have any negative point in the case this feature doesn't work? Like always sending these in header can make a little lower performance?

About Varnish / SSL, your comment were not quite right. Of course, Varnish doesn't work with SSL directly however we always have SSL offloader (proxy) listening on HTTPS port and Varnish will still work normally. So in this case, the cookie feature mostly have no effect.

**Comment by jissereitsma** [comment]
Yes. If the cookie is sent while not being used, it would be bad for performance. Hence, normally, a Varnish configuration is optimized to determine which cookies need to be transferred and which need to be skipped. In this case, the optimization needs to skip this cookie if it is not used. But there is nothing to be done in the Magento extension. This is a thread specifically for the Varnish configuration that you are using and somebody needs to be optimizing that Varnish configuration. The same applies to any other Magento extension that adds cookies.

The SSL offloader you are referring to is the same thing as the SSL terminator I was referring to. Same point, different words.
