### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by eBusinessAtlantique** [yireo/Yireo_LinkPreload#24]
Hello
I installed the module on M2.3.4-p2.
I set to 
Enabled Yes
Use Cookie No
Sikip images Yes

But once my cache is refreshed after saving the settings, the frontend shows 502 Bad Gateway from Nginx.
What kind of problem is it ?

Thanks
Maxime

**Comment by jissereitsma** [comment]
Unfortunately, this is not an error that is helpful. Any error status starting with the number 5 is classified as an internal server error, as in that the system administrator of the hosting environment needs to look into the logs to retrieve the actual logs. Could you ask the system administrator for this? Without the actual internal error, nothing can be debugged and I will need to close this ticket.

By the way, are you sure Magento 2.3.4 patch 2 is used? Because it is not a version I know.

**Comment by eBusinessAtlantique** [comment]
For the version, here is a Magento post : https://magento.com/security/patches/magento-2.3.5-p1-and-2.3.4-p2-security-updates

**Comment by jissereitsma** [comment]
Whoops, my bad. I'm so focused on 2.3.5 and above, that I didn't notice a `p2` for 2.3.4.

**Comment by jissereitsma** [comment]
I'm closing this issue, because there were no further details provided, and the troubleshooting really needs to be kickstarted with the actual error report at hands. If this issue still persists, feel free to re-open the ticket.
