### ISSUE TITLE
Consider testing with move_script_to_bottom

### ISSUE THREAD

**Issue by Leland** [yireo/Yireo_LinkPreload#29]
Hi there!

One interesting thing that occurred to me is using this in conjunction with `move_script_to_bottom` – see: https://github.com/magento/magento2/blame/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Theme/etc/adminhtml/system.xml#L13. This is a setting that will, as the name suggests, move all inline scripts and downloads to just prior to the closing `</body>` tag.

That setting might be used in conjunction with this module to defer all JS by default and then specify a subset of JS to preload – which will then be executed immediately when the parser encounters their `<script>` tag further in the document.

This represents a way to get the "critical" JS loading immediately. If that works like I think it would, that might represent the "ideal" way to use this module!

**Comment by jissereitsma** [comment]
Thanks for the input. While this sounds cool, I'm not sure what it should include - correct me if I'm wrong: 

The 3 or 4 scripts (RequireJS, plus some more) that are loaded via the XML layout are already part of this LinkPreload module, regardless of where their script tag is positioned. So these scripts don't need to be part of the new solution you are proposing.

Inline scripts are inline, so not external. They also are not picked up by this extension, because they are inline and not loaded separately. Through inline scripts, you could load external scripts again: This is the strategy that GTM for instance takes. Unfortunately, such a loading procedure is something you can't parse (easily) in PHP. But this is where manual scripts can be loaded in the LinkPreload configuration by using your XML layout. So again this also doesn't need to be part of the new solution.

This leaves us (as I see it) the scripts loaded via RequireJS. But those are not part of the `move_script_to_bottom` strategy. And RequireJS bundling (properly with `r.js`) is on its own a topic that is quite complex.

So which scripts would need to be optimized how? :)
