### ISSUE TITLE
Use Cookies To Track Pushes and Avoid Unecessary Pushes

### ISSUE THREAD

**Issue by mpchadwick** [yireo/Yireo_LinkPreload#8]
This module could lead to better peformance / eliminate uncessary transfers by using cookies to keep track of resources it has pushed. There are some details on that here...

https://css-tricks.com/cache-aware-server-push/

**Comment by yireo** [comment]
Thanks for the suggestion. Indeed it would. However, earlier we found out that none of the Nginx servers and Apache servers that we are using is actually using Server Push (while they are using other features of HTTP/2 ). So for now, we'll be unable to pick this up ourselves.

**Comment by jissereitsma** [comment]
This is now included in version 1.0.0.

**Comment by jissereitsma** [comment]
Actually, this seems to be based on a misunderstanding. This module includes HTTP/2 `PUSH` via the `Link rel=preload` header, which means that the browser is still in charge of verifying whether the thing that should be preloaded (JS, CSS) is actually in the browser cache or not. So the cookie is not needed after all. It is only with a server-initiated `PUSH` (like through Apache or Nginx) that the browser cache is bypassed.  But that's not the case in this module.

My brain hurts when I start thinking about this in Varnish, because I'm not sure if Varnish simply forwards the `Link rel=preload` header to the client (in which case, the client still is in charge on deciding what to do) or whether it does something different here (using a server-initiated `PUSH`). To be on the safe side, I will make the cookie optional but with a default not to use it.
